// Command cssgen turns the vendored, modern theme CSS into a broadly-compatible
// stylesheet for old browsers, keeping the upstream files byte-identical. It
// applies one feature-adaptation pass per modern CSS feature, in chronological
// order (newest feature first), and writes a <name>.compat.css beside each
// source. Those compat files are what the app embeds and serves.
//
// Target baseline: ~2017 (CSS-grid era), with an eventual stretch to ~2015.
// The build is allowed to be heavy — run it on capable hardware or in CI:
//
//	go run ./tools/cssgen
package main

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// pass adapts one modern CSS feature for old browsers. It returns the
// transformed CSS and a count of adaptations made (for the report).
type pass struct {
	name string
	fn   func(css string) (string, int)
}

// Passes run newest-feature-first. Add clamp, :has, flex-gap, etc. below as
// each is implemented.
var passes = []pass{
	{"text-box", adaptTextBox}, // Chromium 133 / Safari 18.2 (2024–25)
	{":has", adaptHas},         // Chrome 105 / Safari 15.4 / Firefox 121 (2022–23)
	{"logical", adaptLogical},  // Chrome 87 / Safari 14.1 / Firefox 66 (2020–21)
	{"flex-gap", adaptFlexGap}, // Chrome 84 / Safari 14.1 / Firefox 63 (2020–21)
	{"clamp", adaptClamp},      // Chrome 79 / Safari 13.1 / Firefox 75 (2020)
}

var sources = []string{
	"internal/render/static/classic.css",
	"internal/render/static/components.css",
}

func main() {
	for _, src := range sources {
		raw, err := os.ReadFile(src)
		if err != nil {
			fmt.Fprintln(os.Stderr, "read:", err)
			os.Exit(1)
		}
		css := string(raw)
		fmt.Println(src)
		for _, p := range passes {
			var n int
			css, n = p.fn(css)
			fmt.Printf("  %-10s %d adaptation(s)\n", p.name, n)
		}
		if leftover := modernLeftovers(css); len(leftover) > 0 {
			fmt.Fprintf(os.Stderr, "%s: modern CSS survived all passes: %s\n"+
				"add or extend a pass before shipping this compat file\n",
				src, strings.Join(leftover, ", "))
			os.Exit(1)
		}
		out := compatName(src)
		header := fmt.Sprintf("/* GENERATED by tools/cssgen from %s — do not edit.\n"+
			"   Old-browser-compatible build; regenerate with: go run ./tools/cssgen */\n\n",
			filepath.Base(src))
		if err := os.WriteFile(out, []byte(header+css), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write:", err)
			os.Exit(1)
		}
		fmt.Println("  ->", out)
	}
}

func compatName(src string) string {
	ext := filepath.Ext(src)
	return strings.TrimSuffix(src, ext) + ".compat" + ext
}

// minMaxFn matches min()/max() used as functions. The leading guard keeps out
// grid's minmax( (2017-era, fine) and property names like max-width (no paren).
var minMaxFn = regexp.MustCompile(`(^|[^-A-Za-z])(min|max)\(`)

// insetProp matches inset used as a property (the box-shadow keyword has no
// colon after it).
var insetProp = regexp.MustCompile(`\binset[ \t]*:`)

// modernLeftovers is the build tripwire: it scans generated compat CSS
// (comments stripped, so prose mentions don't trip it) for post-2017 syntax no
// pass handled. min()/max() (2020) currently has no source occurrence — our
// components.css precomputes its one former max() — and the logical-property
// probes also catch the forms adaptLogical deliberately skips (-start/-end
// longhands, block-size). If an upstream update introduces any of these, the
// build fails here instead of silently shipping CSS old browsers can't parse.
func modernLeftovers(css string) []string {
	bare := cssComment.ReplaceAllString(css, "")
	var found []string
	for _, probe := range []string{"text-box:", ":has(", "clamp(",
		"margin-block", "margin-inline", "padding-block", "padding-inline",
		"border-block", "border-inline", "block-size", "inline-size"} {
		if strings.Contains(bare, probe) {
			found = append(found, probe)
		}
	}
	if m := minMaxFn.FindStringSubmatch(bare); m != nil {
		found = append(found, m[2]+"(")
	}
	if insetProp.MatchString(bare) {
		found = append(found, "inset:")
	}
	return found
}

// textBoxDecl matches a whole `text-box: …;` declaration line.
var textBoxDecl = regexp.MustCompile(`(?m)^[ \t]*text-box:[^;]*;[ \t]*\r?\n?`)

// adaptTextBox handles `text-box: trim-both cap alphabetic` (Chromium 133 /
// Safari 18.2) — precise cap-height trimming only the newest browsers support.
// Rather than carry two rendering paths (an @supports fallback isn't
// pixel-identical anyway), the compat build *drops* text-box so every browser
// renders the same.
//
// The untrimmed design is not ours to invent: Firefox has no text-box, so the
// theme's own `@-moz-document url-prefix()` block IS the author's no-text-box
// rendering — tighter h1–h4/p margins (1.15rem vs 1.75rem), reduced main
// padding, .imgf-title h4 pull-up, .postmeta, .lcars-list markers, .meta-data
// height. Upstream, only Firefox applies it; in the compat build no browser
// has text-box, so those compensations are hoisted to unconditional rules for
// everyone (audited: the elements the author leaves uncompensated — data
// cascade rows, gallery captions, blockquote — shift <2px untrimmed).
//
// The one exception is the author's .lcars-text-bar heading fix (top: -.7vh):
// it's excluded from the hoist because the transform-based centering appended
// below replaces it (Playwright-measured, engine-consistent — see comment).
func adaptTextBox(css string) (string, int) {
	stripped := textBoxDecl.ReplaceAllString(css, "")
	n := strings.Count(css, "text-box:") - strings.Count(stripped, "text-box:")
	if n == 0 {
		return css, 0
	}
	stripped = hoistMozBlock(stripped)
	return stripped + "\n" + textBoxCentering, n
}

// hoistMozBlock unwraps the theme's `@-moz-document url-prefix() { … }` block —
// the author's no-text-box compensations (see adaptTextBox) — so its rules
// apply on every browser, minus the .lcars-text-bar rules that our appended
// centering supersedes. The rules stay at the block's position (end of file),
// so they override the base rules exactly as they do in upstream Firefox.
func hoistMozBlock(css string) string {
	i := strings.Index(css, "@-moz-document")
	if i < 0 {
		return css
	}
	brace := strings.Index(css[i:], "{")
	if brace < 0 {
		return css
	}
	brace += i
	k := blockEnd(css, brace)
	contents := dropRules(css[brace+1:k-1], ".lcars-text-bar")
	return css[:i] +
		"/* cssgen: the @-moz-document url-prefix() block is the theme's own\n" +
		"   no-text-box rendering (Firefox never shipped text-box). The compat\n" +
		"   build drops text-box everywhere, so these apply unconditionally;\n" +
		"   the .lcars-text-bar rules are replaced by the centering below. */" +
		contents + css[k:]
}

// dropRules removes top-level rules whose selector contains sub, keeping
// everything else byte-for-byte.
func dropRules(css, sub string) string {
	var out strings.Builder
	i := 0
	for i < len(css) {
		brace, semi := nextDelim(css, i)
		if semi != -1 {
			out.WriteString(css[i : semi+1])
			i = semi + 1
			continue
		}
		if brace == -1 {
			out.WriteString(css[i:])
			break
		}
		k := blockEnd(css, brace)
		if !strings.Contains(css[i:brace], sub) {
			out.WriteString(css[i:k])
		}
		i = k
	}
	return out.String()
}

const textBoxCentering = `/* cssgen: text-box dropped for compat. The heading (black title box) is taller
   than the bar, so it must be centered on it. Flex-centering an overflowing item
   is inconsistent across engines (Firefox drifts it low), so center via
   absolute + translateY(-50%), which is engine-consistent. Then a small padding
   bias shifts the text up to optically center the cap height (glyphs sit ~0.07em
   low in the line box without text-box trimming — same in both engines once the
   box is correctly centered). Playwright-measured. */
.lcars-text-bar { position: relative; }
.lcars-text-bar h2,
.lcars-text-bar h3,
.lcars-text-bar h4,
.lcars-text-bar span {
  position: absolute;
  top: 50%;
  left: 0;
  transform: translateY(-50%);
  height: auto;
  line-height: 1;
  padding-top: calc(0.3em - 0.07em);
  padding-bottom: calc(0.3em + 0.07em);
}
.lcars-text-bar.the-end h2,
.lcars-text-bar.the-end h3,
.lcars-text-bar.the-end h4,
.lcars-text-bar.the-end span {
  left: auto;
  right: 0;
}
`

// adaptHas removes rules whose selector uses :has() — the parent selector
// (Chrome 105 / Safari 15.4 / Firefox 121, 2022–23). There is no pre-2022 way to
// match "an element that contains X", and old browsers already treat an unknown
// :has() selector as invalid and drop the whole rule. Dropping it in the compat
// build too keeps the file free of :has(), so a modern browser renders exactly
// what an old one does (neither applies these rules) — verifiable on modern
// hardware, consistent with how clamp() and text-box are handled.
//
// The theme has three :has() cases, all page-layout tweaks:
//   - .data-cascade-button-group:has(.header-content)  (row-gap / nav / nth-child)
//   - main:has(.floor-heading) > *:nth-child(2)         (margin-top: 0)
//   - footer:has(.footer-frame)                         (font-size: inherit)
//
// None of them exists to trigger today: our app never emits .header-content,
// .floor-heading, or .footer-frame (we build LCARS from components, and the
// button-group/data-cascade are now separate components), and in fact no live
// TheLCARS.com page emits them either — the classes ship in the stylesheet with
// no consumer. So stripping all three is a no-op now.
//
// If we ever want one of these effects on old browsers, the replacement is a
// server-set marker class: rewrite `X:has(.Y)` to `X.has-Y` here and have the
// template add `has-Y` to X whenever it renders a .Y inside it. That reproduces
// the effect identically on every browser (still verifiable on a modern one)
// without needing :has(). We don't emit `.has-Y` markers yet because nothing
// consumes them — this is the hook for when something does.
func adaptHas(css string) (string, int) {
	return stripHas(css)
}

// cssComment matches a /* … */ CSS comment (used to tell if a block is empty).
var cssComment = regexp.MustCompile(`/\*[\s\S]*?\*/`)

// skipComment returns the index just past a /*…*/ comment starting at i, or i
// unchanged if s[i:] doesn't start one. The node walkers use it so a ; { or }
// inside a comment can't be mistaken for CSS structure.
func skipComment(s string, i int) int {
	if strings.HasPrefix(s[i:], "/*") {
		if end := strings.Index(s[i+2:], "*/"); end >= 0 {
			return i + 2 + end + 2
		}
		return len(s)
	}
	return i
}

// cleanSelector strips comments and collapses whitespace in a rule header, for
// use in generated rules (@media fallbacks etc.) where the original header's
// comments and line breaks would be noise — or worse, get split from their
// opener.
func cleanSelector(header string) string {
	return strings.Join(strings.Fields(cssComment.ReplaceAllString(header, "")), " ")
}

// nextDelim finds the next structural '{' or ';' from i, skipping comments.
// Exactly one of the results is >= 0 (whichever comes first), or both are -1.
func nextDelim(css string, i int) (brace, semi int) {
	for k := i; k < len(css); k++ {
		if j := skipComment(css, k); j > k {
			k = j - 1
			continue
		}
		if css[k] == '{' {
			return k, -1
		}
		if css[k] == ';' {
			return -1, k
		}
	}
	return -1, -1
}

// blockEnd returns the index just past the '}' that closes the block whose '{'
// sits at brace, skipping comments while counting depth.
func blockEnd(css string, brace int) int {
	depth := 1
	for k := brace + 1; k < len(css); k++ {
		if j := skipComment(css, k); j > k {
			k = j - 1
			continue
		}
		switch css[k] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return k + 1
			}
		}
	}
	return len(css)
}

// isBlank reports whether s is only whitespace and comments (no rules/decls).
func isBlank(s string) bool {
	return strings.TrimSpace(cssComment.ReplaceAllString(s, "")) == ""
}

// stripHas walks the top-level nodes (mirroring rewriteBlock's parser): it drops
// qualified rules selected via :has(), recurses into conditional group at-rules
// (@media/@supports/@-moz-document), and drops an at-rule that :has removal
// leaves empty. Rules without :has() are reproduced byte-for-byte.
func stripHas(css string) (string, int) {
	var out strings.Builder
	total, i := 0, 0
	for i < len(css) {
		brace, semi := nextDelim(css, i)
		if semi != -1 { // e.g. @charset "…";
			out.WriteString(css[i : semi+1])
			i = semi + 1
			continue
		}
		if brace == -1 {
			out.WriteString(css[i:])
			break
		}
		header := css[i:brace]
		k := blockEnd(css, brace)
		body := css[brace+1 : k-1]
		if strings.HasPrefix(cleanSelector(header), "@") {
			inner, n := stripHas(body)
			total += n
			if n > 0 && isBlank(inner) { // at-rule emptied by the strip: drop it
			} else {
				out.WriteString(header + "{" + inner + "}")
			}
		} else if sel, keep, n := stripHasSelector(header); n == 0 {
			out.WriteString(header + "{" + body + "}") // no :has(): unchanged
		} else {
			total += n
			if keep { // some non-:has() selectors survived the comma list
				out.WriteString(sel + "{" + body + "}")
			} // else: whole rule dropped
		}
		i = k
	}
	return out.String(), total
}

// stripHasSelector inspects a rule header's selector list. It returns the header
// to keep, whether any selector survived, and 1 if the rule used :has() (else 0
// with the header untouched). :has()-bearing selectors are removed from the
// comma list; if that empties it, keep is false and the caller drops the rule.
func stripHasSelector(header string) (string, bool, int) {
	if !strings.Contains(header, ":has(") {
		return header, true, 0
	}
	var kept []string
	for _, s := range splitTopComma(strings.TrimSpace(header)) {
		if !strings.Contains(s, ":has(") {
			kept = append(kept, strings.TrimSpace(s))
		}
	}
	if len(kept) == 0 {
		return "", false, 1
	}
	lead := header[:len(header)-len(strings.TrimLeft(header, " \t\r\n"))]
	return lead + strings.Join(kept, ",\n"), true, 1
}

// logicalDecl matches one logical-property declaration: margin-/padding-block
// or -inline (1–2 values), border-block (a border shorthand), or the inset
// shorthand (1–4 values). The site is English (horizontal-tb, LTR), so the
// physical mapping is static: block = top/bottom, inline = left/right, and
// inset follows the TRBL order. \b keeps `inset` in a box-shadow value (no
// colon) from matching.
var logicalDecl = regexp.MustCompile(`\b(margin-block|margin-inline|padding-block|padding-inline|border-block|inset)[ \t]*:[ \t]*([^;{}]+);`)

// adaptLogical rewrites logical shorthands (Chrome 87 / Safari 14.1, 2020–21)
// to the physical longhands every browser understands, in place — same value,
// same specificity, so this is exact on modern and old browsers alike. Only the
// shorthand forms the theme uses are handled; a -start/-end longhand or
// block-size would not match, survive to the compat file, and trip the
// modernLeftovers build check so it gets handled deliberately.
func adaptLogical(css string) (string, int) {
	n := 0
	out := logicalDecl.ReplaceAllStringFunc(css, func(m string) string {
		sm := logicalDecl.FindStringSubmatch(m)
		prop, val := sm[1], strings.TrimSpace(sm[2])
		bang := ""
		if k := strings.Index(val, "!"); k >= 0 { // carry !important onto each longhand
			bang = " " + strings.TrimSpace(val[k:])
			val = strings.TrimSpace(val[:k])
		}
		var decls []string
		emit := func(p, v string) { decls = append(decls, p+": "+v+bang+";") }
		switch prop {
		case "border-block": // a border shorthand applied to both edges, not split
			emit("border-top", val)
			emit("border-bottom", val)
		case "inset":
			v := splitTopSpace(val)
			t, r, b, l := v[0], v[0], v[0], v[0]
			switch len(v) {
			case 2:
				r, l = v[1], v[1]
			case 3:
				r, l, b = v[1], v[1], v[2]
			case 4:
				r, b, l = v[1], v[2], v[3]
			}
			emit("top", t)
			emit("right", r)
			emit("bottom", b)
			emit("left", l)
		default: // margin/padding -block/-inline: 1–2 values
			v := splitTopSpace(val)
			a, b := v[0], v[0]
			if len(v) > 1 {
				b = v[1]
			}
			base := prop[:strings.Index(prop, "-")] // margin | padding
			if strings.HasSuffix(prop, "-block") {
				emit(base+"-top", a)
				emit(base+"-bottom", b)
			} else {
				emit(base+"-left", a)
				emit(base+"-right", b)
			}
		}
		n++
		return strings.Join(decls, " ")
	})
	return out, n
}

// splitTopSpace splits a declaration value on whitespace at parenthesis depth 0,
// so a space inside var(--x, fallback) or calc() doesn't split a component.
func splitTopSpace(s string) []string {
	var parts []string
	depth, start := 0, -1
	for i := 0; i < len(s); i++ {
		switch {
		case s[i] == '(':
			depth++
		case s[i] == ')':
			depth--
		case (s[i] == ' ' || s[i] == '\t') && depth == 0:
			if start >= 0 {
				parts = append(parts, s[start:i])
				start = -1
			}
			continue
		}
		if start < 0 {
			start = i
		}
	}
	if start >= 0 {
		parts = append(parts, s[start:])
	}
	return parts
}

// flexInfo is the layout of a selector, gathered across all its rules so a gap
// set in a @media block can still see the display/direction/wrap/margins from
// the base rule.
type flexInfo struct {
	isFlex                    bool
	column                    bool   // flex-direction: column(-reverse)
	wrap                      bool   // flex-wrap: wrap(-reverse)
	spaced                    bool   // justify-content: space-between/around/evenly
	mTop, mBot, mLeft, mRight string // container's own margins, for folding ("" = none)
}

// flexLayouts maps a trimmed selector to its flexInfo. Rebuilt per file by
// adaptFlexGap before the pass runs.
var flexLayouts map[string]flexInfo

// adaptFlexGap makes flex-container gap work on browsers that only did grid gap
// (flex gap arrived Chrome 84 / Safari 14.1, 2020–21). GRID gap is ~2017 and is
// left untouched; only flex `gap`/`row-gap`/`column-gap` is rewritten. As with
// clamp, the gap is *removed* and the spacing reproduced another way both old
// and new browsers share (so it's verifiable on modern hardware):
//
//   - non-wrapping containers → margins between adjacent items:
//     `SEL > * + * { margin-top|left: <gap> }` (top for column flow, left for row).
//   - wrapping / two-axis containers → the negative-margin technique, per axis
//     present, folding any margin the container already has:
//     `SEL { margin-*: calc(existing - <gap>/2) }` and
//     `SEL > * { margin-*: calc(<gap>/2) }`.
//     Half the gap on every child, cancelled at the outer edge by the container,
//     leaves an even gutter that survives wrapping.
func adaptFlexGap(css string) (string, int) {
	flexLayouts = scanFlexLayouts(css)
	return rewriteGap(css)
}

// scanFlexLayouts reads every rule (mirroring the node walk) and records each
// selector's display/direction/wrap and own margins, merged across its rules.
func scanFlexLayouts(css string) map[string]flexInfo {
	m := map[string]flexInfo{}
	eachRule(css, func(sel, body string) {
		info := m[sel]
		if v, ok := declValue(body, "display"); ok && strings.Contains(v, "flex") {
			info.isFlex = true
		}
		if v, ok := declValue(body, "flex-direction"); ok && strings.HasPrefix(v, "column") {
			info.column = true
		}
		if v, ok := declValue(body, "flex-wrap"); ok && strings.HasPrefix(v, "wrap") {
			info.wrap = true
		}
		if v, ok := declValue(body, "justify-content"); ok && strings.HasPrefix(v, "space") {
			info.spaced = true
		}
		mergeMargins(body, &info)
		m[sel] = info
	})
	return m
}

// mergeMargins folds a rule's margin declarations into info (longhands,
// margin-block/inline, and single-value margin shorthand — enough for the
// theme's containers).
func mergeMargins(body string, info *flexInfo) {
	set := func(dst *string, v string) {
		if v != "" {
			*dst = v
		}
	}
	if v, ok := declValue(body, "margin-top"); ok {
		set(&info.mTop, v)
	}
	if v, ok := declValue(body, "margin-bottom"); ok {
		set(&info.mBot, v)
	}
	if v, ok := declValue(body, "margin-left"); ok {
		set(&info.mLeft, v)
	}
	if v, ok := declValue(body, "margin-right"); ok {
		set(&info.mRight, v)
	}
	if v, ok := declValue(body, "margin-block"); ok {
		t, b := pair(v)
		set(&info.mTop, t)
		set(&info.mBot, b)
	}
	if v, ok := declValue(body, "margin-inline"); ok {
		l, r := pair(v)
		set(&info.mLeft, l)
		set(&info.mRight, r)
	}
	if v, ok := declValue(body, "margin"); ok {
		if f := strings.Fields(v); len(f) == 1 {
			set(&info.mTop, f[0])
			set(&info.mBot, f[0])
			set(&info.mLeft, f[0])
			set(&info.mRight, f[0])
		}
	}
}

// pair splits a one-or-two-value shorthand ("2rem" or "2rem 1rem") into its two
// sides (first, second-or-first).
func pair(v string) (string, string) {
	f := strings.Fields(v)
	if len(f) == 0 {
		return "", ""
	}
	if len(f) == 1 {
		return f[0], f[0]
	}
	return f[0], f[1]
}

// declValue returns the value of property prop in a rule body (declarations only)
// and whether it was present. Exact property match (so "margin" won't hit
// "margin-block").
func declValue(body, prop string) (string, bool) {
	for _, part := range strings.Split(body, ";") {
		p := strings.TrimSpace(part)
		if strings.HasPrefix(p, prop) {
			rest := strings.TrimSpace(p[len(prop):])
			if strings.HasPrefix(rest, ":") {
				return strings.TrimSpace(rest[1:]), true
			}
		}
	}
	return "", false
}

// rewriteGap walks the nodes, and in flex rules strips the gap declarations and
// appends the margin-based fallback rules right after the container rule (in the
// same @media context). Grid and non-flex rules are reproduced byte-for-byte.
func rewriteGap(css string) (string, int) {
	var out strings.Builder
	total, i := 0, 0
	for i < len(css) {
		brace, semi := nextDelim(css, i)
		if semi != -1 {
			out.WriteString(css[i : semi+1])
			i = semi + 1
			continue
		}
		if brace == -1 {
			out.WriteString(css[i:])
			break
		}
		header := css[i:brace]
		k := blockEnd(css, brace)
		body := css[brace+1 : k-1]
		sel := cleanSelector(header)
		if strings.HasPrefix(sel, "@") {
			inner, n := rewriteGap(body)
			total += n
			out.WriteString(header + "{" + inner + "}")
		} else if info := flexLayouts[sel]; info.isFlex {
			newBody, gaps := stripFlexGaps(body)
			var fb strings.Builder
			for _, g := range gaps {
				fb.WriteString(gapFallback(sel, info, g[0], g[1]))
				total++
			}
			out.WriteString(header + "{" + newBody + "}" + fb.String())
		} else {
			out.WriteString(header + "{" + body + "}")
		}
		i = k
	}
	return out.String(), total
}

// stripFlexGaps splits a rule body into declarations, drops the gap ones, and
// returns the rebuilt body plus the {prop, value} of each gap removed. Splitting
// (rather than a line regex) handles gaps written inline on a one-line rule as
// well as on their own line.
func stripFlexGaps(body string) (string, [][2]string) {
	var kept []string
	var gaps [][2]string
	for _, part := range strings.Split(body, ";") {
		if prop, val, ok := gapDecl(strings.TrimSpace(part)); ok {
			gaps = append(gaps, [2]string{prop, val})
			continue
		}
		kept = append(kept, part)
	}
	return strings.Join(kept, ";"), gaps
}

// gapDecl reports whether a trimmed declaration is gap/row-gap/column-gap and
// returns its property and value.
func gapDecl(p string) (prop, val string, ok bool) {
	for _, name := range []string{"gap", "row-gap", "column-gap"} {
		if strings.HasPrefix(p, name) {
			rest := strings.TrimSpace(p[len(name):])
			if strings.HasPrefix(rest, ":") {
				return name, strings.TrimSpace(rest[1:]), true
			}
		}
	}
	return "", "", false
}

// gapFallback builds the margin rules that stand in for one flex gap declaration.
func gapFallback(sel string, info flexInfo, prop, val string) string {
	rowGap, colGap := "", ""
	switch prop {
	case "row-gap":
		rowGap = val
	case "column-gap":
		colGap = val
	case "gap":
		rowGap, colGap = pair(val)
	}
	var b strings.Builder
	if !info.wrap { // single line: only the main-axis gap spaces items
		if info.spaced {
			// justify-content: space-* already distributes items along the main
			// axis; gap is just a minimum gutter there, and a margin fights the
			// distribution rather than reproducing it. Dropping the gap matches
			// what the same space-* container does without gap support.
			return ""
		}
		if info.column && rowGap != "" {
			fmt.Fprintf(&b, "\n%s > * + * { margin-top: %s; }", sel, rowGap)
		} else if !info.column && colGap != "" {
			fmt.Fprintf(&b, "\n%s > * + * { margin-left: %s; }", sel, colGap)
		}
		return b.String()
	}
	var cont, child []string
	if colGap != "" {
		cont = append(cont, fold("left", info.mLeft, colGap), fold("right", info.mRight, colGap))
		child = append(child, "margin-left: calc("+colGap+" / 2)", "margin-right: calc("+colGap+" / 2)")
	}
	if rowGap != "" {
		cont = append(cont, fold("top", info.mTop, rowGap), fold("bottom", info.mBot, rowGap))
		child = append(child, "margin-top: calc("+rowGap+" / 2)", "margin-bottom: calc("+rowGap+" / 2)")
	}
	fmt.Fprintf(&b, "\n%s { %s; }", sel, strings.Join(cont, "; "))
	fmt.Fprintf(&b, "\n%s > * { %s; }", sel, strings.Join(child, "; "))
	return b.String()
}

// fold returns the container's margin on one side: half the gap pulled back to
// cancel the children's outer half-gap, plus any margin the container already
// had on that side.
func fold(side, existing, gap string) string {
	if existing == "" {
		return "margin-" + side + ": calc(" + gap + " / -2)"
	}
	return "margin-" + side + ": calc(" + existing + " - " + gap + " / 2)"
}

// eachRule invokes fn(selector, body) for every qualified rule at any nesting,
// recursing into conditional group at-rules. Read-only companion to the
// transforming node walkers.
func eachRule(css string, fn func(sel, body string)) {
	i := 0
	for i < len(css) {
		brace, semi := nextDelim(css, i)
		if semi != -1 {
			i = semi + 1
			continue
		}
		if brace == -1 {
			break
		}
		header := css[i:brace]
		k := blockEnd(css, brace)
		body := css[brace+1 : k-1]
		if sel := cleanSelector(header); strings.HasPrefix(sel, "@") {
			eachRule(body, fn)
		} else {
			fn(sel, body)
		}
		i = k
	}
}

// initialRootPx is the browser default font size. A `font-size: Nrem` on :root
// resolves N against this (rem on the root element uses the inherited/initial
// size), which is how we turn the theme's root font-size rules into px.
const initialRootPx = 16.0

// remRegime says the root font-size is remPx for viewports up to maxWidth px.
type remRegime struct {
	maxWidth float64 // inclusive upper bound; math.Inf(1) for the base regime
	remPx    float64
}

// remRegimes holds the stylesheet's root font-size by viewport, ascending by
// maxWidth with the base (Inf) last. This theme sizes :root responsively
// (font-size: 1.375rem, dropping to 1.2rem under 1300px), so `rem` — and thus
// every rem-based clamp bound — changes with the viewport. loadRemRegimes fills
// this from the CSS before the clamp pass, so breakpoints use the rem actually
// in effect where they land. Empty means a constant 16px root.
var remRegimes []remRegime

// rootBaseRe grabs the first (non-media) `:root { … font-size: Nrem }`; the base
// root size. rootMediaRe grabs each `@media (max-width: W) { … :root { …
// font-size: Nrem } }` override.
// The [^-\w] before font-size is a boundary so the custom property
// --dc-font-size can't false-match; [^{}]*? keeps the scan inside one rule so a
// media block without its own root font-size can't borrow a sibling's.
var (
	rootBaseRe  = regexp.MustCompile(`:root\s*\{[^{}]*?[^-\w]font-size:\s*([0-9.]+)rem`)
	rootMediaRe = regexp.MustCompile(`@media\s*\(max-width:\s*([0-9.]+)px\)\s*\{[^{}]*?:root\s*\{[^{}]*?[^-\w]font-size:\s*([0-9.]+)rem`)
)

// loadRemRegimes derives the responsive root font-size table from the CSS. If no
// :root font-size is found, it falls back to a constant 16px root.
func loadRemRegimes(css string) {
	remRegimes = nil
	base := rootBaseRe.FindStringSubmatch(css)
	if base == nil {
		remRegimes = []remRegime{{math.Inf(1), initialRootPx}}
		return
	}
	for _, m := range rootMediaRe.FindAllStringSubmatch(css, -1) {
		w, _ := strconv.ParseFloat(m[1], 64)
		r, _ := strconv.ParseFloat(m[2], 64)
		remRegimes = append(remRegimes, remRegime{w, r * initialRootPx})
	}
	// ascending by maxWidth so a breakpoint can be tested regime by regime
	for i := 1; i < len(remRegimes); i++ {
		for j := i; j > 0 && remRegimes[j].maxWidth < remRegimes[j-1].maxWidth; j-- {
			remRegimes[j], remRegimes[j-1] = remRegimes[j-1], remRegimes[j]
		}
	}
	baseRem, _ := strconv.ParseFloat(base[1], 64)
	remRegimes = append(remRegimes, remRegime{math.Inf(1), baseRem * initialRootPx})
}

// clampDeclRe matches a single declaration whose value contains clamp(...).
// Group 1 is the "property:" head (with any leading whitespace); group 2 is the
// value up to (not including) the terminating semicolon. It deliberately stops
// at ; { } so it stays within one declaration; parenthesis nesting inside the
// value is handled by scanning, not the regexp.
var clampDeclRe = regexp.MustCompile(`([ \t]*[A-Za-z-]+\s*:\s*)([^;{}]*clamp\([^;{}]*);`)

// adaptClamp rewrites clamp()-bearing declarations for browsers without clamp()
// (pre Chrome 79 / Firefox 75 / Safari 13.1, 2020). clamp(MIN, PREFERRED, MAX)
// has no pre-2020 equivalent, so the compat build reproduces its behaviour with
// media queries instead. The declaration keeps the PREFERRED (middle) value —
// which scales with the viewport — and we append, right after the rule, two
// media queries that pin the property to MIN below the viewport size where
// PREFERRED would drop under MIN, and to MAX above the size where PREFERRED
// would exceed MAX. For width: clamp(200px, 50vw, 600px): 50vw == 200px at a
// 400px viewport and == 600px at 1200px, so:
//
//	width: 50vw;                                     (in the rule)
//	@media (max-width: 400px)  { sel { width: 200px } }
//	@media (min-width: 1200px) { sel { width: 600px } }
//
// Because clamp() is gone entirely, a modern browser renders exactly what an old
// one does, so compatibility can be checked on modern hardware. The media
// queries are emitted as siblings after the rule (old CSS can't nest them inside
// a rule) and, sitting later in source order at equal specificity, correctly
// win when they match — while any of the theme's own later media queries still
// override them, mirroring the upstream cascade.
func adaptClamp(css string) (string, int) {
	loadRemRegimes(css)
	return rewriteBlock(css)
}

// rewriteBlock walks the top-level nodes of a stylesheet fragment. Qualified
// rules get their clamps rewritten and media-query fallbacks appended after the
// rule; conditional group at-rules (@media, @supports, @-moz-document) are
// recursed into so a clamp nested inside one is handled in its own context.
// Anything without a clamp is reproduced byte-for-byte.
func rewriteBlock(css string) (string, int) {
	var out strings.Builder
	total, i := 0, 0
	for i < len(css) {
		brace, semi := nextDelim(css, i)
		if semi != -1 { // a statement like @charset "…";
			out.WriteString(css[i : semi+1])
			i = semi + 1
			continue
		}
		if brace == -1 { // no more blocks: trailing text
			out.WriteString(css[i:])
			break
		}
		header := css[i:brace] // includes any leading comments/whitespace
		k := blockEnd(css, brace)
		body := css[brace+1 : k-1]
		if strings.HasPrefix(cleanSelector(header), "@") {
			inner, n := rewriteBlock(body)
			total += n
			out.WriteString(header + "{" + inner + "}")
		} else {
			newBody, media, n := rewriteRule(cleanSelector(header), body)
			total += n
			out.WriteString(header + "{" + newBody + "}" + media)
		}
		i = k
	}
	return out.String(), total
}

// mediaGroup is one @media block to emit: several declarations that share the
// same feature test (e.g. "max-width: 700px"), scoped to a rule's selector.
type mediaGroup struct {
	feature string // e.g. "max-width" or "min-height"
	bp      int    // breakpoint in px
	decls   []string
}

// rewriteRule rewrites the clamp declarations in one rule body to their
// PREFERRED value and returns (newBody, mediaText, count). mediaText is the
// media-query fallback blocks to place immediately after the rule.
func rewriteRule(selector, body string) (string, string, int) {
	var groups []*mediaGroup
	byKey := map[string]*mediaGroup{}
	add := func(feature string, bp int, decl string) {
		key := fmt.Sprintf("%s|%d", feature, bp)
		g := byKey[key]
		if g == nil {
			g = &mediaGroup{feature: feature, bp: bp}
			byKey[key] = g
			groups = append(groups, g)
		}
		g.decls = append(g.decls, decl)
	}

	total := 0
	newBody := clampDeclRe.ReplaceAllStringFunc(body, func(m string) string {
		sm := clampDeclRe.FindStringSubmatch(m)
		head, value := sm[1], sm[2]
		c, ok := analyzeClamp(value)
		if !ok {
			return m // not a form we understand; leave untouched
		}
		total++
		prop := strings.TrimSpace(head) // e.g. "font-size:"
		if c.axis != "" {               // responsive: emit MIN/MAX breakpoints
			dim := "width"
			if c.axis == "vh" {
				dim = "height"
			}
			if c.lowBP > 0 {
				add("max-"+dim, c.lowBP, prop+" "+c.minValue+";")
			}
			if c.highBP > 0 {
				add("min-"+dim, c.highBP, prop+" "+c.maxValue+";")
			}
		}
		return head + c.prefValue + ";"
	})
	if total == 0 {
		return body, "", 0
	}

	var media strings.Builder
	media.WriteString("\n/* cssgen: clamp() removed; the breakpoints below reproduce its" +
		" MIN/MAX bounds so an old browser matches a modern one. */")
	for _, g := range groups {
		media.WriteString(fmt.Sprintf("\n@media (%s: %dpx) { %s { %s } }",
			g.feature, g.bp, selector, strings.Join(g.decls, " ")))
	}
	return newBody, media.String(), total
}

// clampInfo is the result of analysing one clamp()-bearing value.
type clampInfo struct {
	prefValue, minValue, maxValue string // the value with clamp() swapped for each arg
	axis                          string // "vw", "vh", or "" if not viewport-responsive
	lowBP, highBP                 int    // viewport px where PREFERRED meets MIN / MAX
}

// analyzeClamp finds the (single) clamp() in a declaration value and works out
// the PREFERRED/MIN/MAX value strings plus the viewport breakpoints. It returns
// ok=false for anything it can't reduce to MIN + coeff*viewport (so the caller
// leaves it alone rather than emit something wrong).
func analyzeClamp(value string) (clampInfo, bool) {
	i := strings.Index(value, "clamp(")
	if i < 0 {
		return clampInfo{}, false
	}
	open := i + len("clamp(") - 1
	depth, close := 0, -1
	for j := open; j < len(value); j++ {
		switch value[j] {
		case '(':
			depth++
		case ')':
			depth--
		}
		if depth == 0 {
			close = j
			break
		}
	}
	if close < 0 {
		return clampInfo{}, false
	}
	parts := splitTopComma(value[open+1 : close])
	if len(parts) != 3 {
		return clampInfo{}, false
	}
	minArg := strings.TrimSpace(parts[0])
	prefArg := strings.TrimSpace(parts[1])
	maxArg := strings.TrimSpace(parts[2])

	swap := func(arg string) string { return value[:i] + arg + value[close+1:] }
	pref := prefArg
	if isExpr(pref) {
		pref = "calc(" + pref + ")"
	}
	info := clampInfo{prefValue: swap(pref), minValue: swap(minArg), maxValue: swap(maxArg)}

	prefLin, ok := parseLin(prefArg)
	if !ok || (prefLin.vw == 0 && prefLin.vh == 0) { // fixed-only: no breakpoints
		return info, ok
	}
	minLin, ok1 := parseLin(minArg)
	maxLin, ok2 := parseLin(maxArg)
	if !ok1 || !ok2 {
		return clampInfo{}, false
	}
	coeff := prefLin.vw
	info.axis = "vw"
	if prefLin.vh != 0 {
		coeff, info.axis = prefLin.vh, "vh"
	}
	// Solve for the viewport V where PREFERRED meets MIN / MAX, using the root
	// font-size in effect where V lands (rem bounds are viewport-responsive).
	if bp, ok := crossover(prefLin, minLin, coeff); ok {
		info.lowBP = bp
	}
	if bp, ok := crossover(prefLin, maxLin, coeff); ok {
		info.highBP = bp
	}
	return info, true
}

// lin is a length as pxPart + rem*rootRem + vw*(width/100) + vh*(height/100), so
// a clamp bound or preferred value can be evaluated once the root font-size and
// viewport are known.
type lin struct{ px, rem, vw, vh float64 }

// parseLin reads a space-and-plus-separated length sum (e.g. "0.75rem + 4vw",
// "16px", "2vw") into a lin. ok is false for unknown units or malformed terms.
func parseLin(s string) (lin, bool) {
	var L lin
	for _, raw := range strings.Split(s, "+") {
		term := strings.TrimSpace(raw)
		if term == "" {
			return lin{}, false
		}
		var unit string
		for _, u := range []string{"px", "rem", "vw", "vh"} {
			if strings.HasSuffix(term, u) {
				unit = u
				break
			}
		}
		if unit == "" {
			return lin{}, false
		}
		v, err := strconv.ParseFloat(strings.TrimSpace(term[:len(term)-len(unit)]), 64)
		if err != nil {
			return lin{}, false
		}
		switch unit {
		case "px":
			L.px += v
		case "rem":
			L.rem += v
		case "vw":
			L.vw += v
		case "vh":
			L.vh += v
		}
	}
	return L, true
}

// crossover returns the viewport px where PREFERRED (p) equals target (t, a
// clamp bound with no viewport term), rounded. Because rem bounds depend on the
// viewport-responsive root font-size, it solves within each rem regime and keeps
// the answer that lands in that regime's viewport range. ok is false if none is
// self-consistent (e.g. the crossing is masked by a root font-size step).
func crossover(p, t lin, coeff float64) (int, bool) {
	prev := 0.0
	for _, rg := range remRegimes {
		// p.px + p.rem*R + coeff*V/100 == t.px + t.rem*R
		v := (t.px - p.px + (t.rem-p.rem)*rg.remPx) * 100 / coeff
		if v > prev && v <= rg.maxWidth {
			return int(math.Round(v)), true
		}
		prev = rg.maxWidth
	}
	return 0, false
}

// splitTopComma splits on commas that sit at parenthesis depth 0, so commas
// inside a nested calc()/min()/max() don't split an argument.
func splitTopComma(s string) []string {
	var parts []string
	depth, start := 0, 0
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '(':
			depth++
		case ')':
			depth--
		case ',':
			if depth == 0 {
				parts = append(parts, s[start:i])
				start = i + 1
			}
		}
	}
	return append(parts, s[start:])
}

// isExpr reports whether s is a bare arithmetic expression (has a top-level
// operator) rather than a single token or already-wrapped function. Operators
// are matched with surrounding spaces, matching CSS calc() syntax where + and -
// must be space-separated (this also avoids mistaking a negative number or a
// hyphenated unit for an operator).
func isExpr(s string) bool {
	if strings.HasPrefix(s, "calc(") || strings.HasPrefix(s, "min(") || strings.HasPrefix(s, "max(") {
		return false
	}
	return strings.Contains(s, " + ") || strings.Contains(s, " - ") ||
		strings.Contains(s, " * ") || strings.Contains(s, " / ")
}
