// Command cssgen turns the vendored, modern theme CSS into a broadly-compatible
// stylesheet for old browsers, keeping the upstream files byte-identical. It
// applies one feature-adaptation pass per modern CSS feature, in chronological
// order (newest feature first), and writes a <name>.compat.css beside each
// source. Those compat files are what the app embeds and serves.
//
// Target baseline: ~2017 (CSS-grid era), with an eventual stretch to ~2015.
// The build is allowed to be heavy — run it on capable hardware or in CI:
//
//	go run ./tools/cssgen
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// pass adapts one modern CSS feature for old browsers. It returns the
// transformed CSS and a count of adaptations made (for the report).
type pass struct {
	name string
	fn   func(css string) (string, int)
}

// Passes run newest-feature-first. Add clamp, :has, flex-gap, etc. below as
// each is implemented.
var passes = []pass{
	{"text-box", adaptTextBox}, // Chromium 133 / Safari 18.2 (2024–25)
}

var sources = []string{
	"internal/render/static/classic.css",
	"internal/render/static/components.css",
}

func main() {
	for _, src := range sources {
		raw, err := os.ReadFile(src)
		if err != nil {
			fmt.Fprintln(os.Stderr, "read:", err)
			os.Exit(1)
		}
		css := string(raw)
		fmt.Println(src)
		for _, p := range passes {
			var n int
			css, n = p.fn(css)
			fmt.Printf("  %-10s %d adaptation(s)\n", p.name, n)
		}
		out := compatName(src)
		header := fmt.Sprintf("/* GENERATED by tools/cssgen from %s — do not edit.\n"+
			"   Old-browser-compatible build; regenerate with: go run ./tools/cssgen */\n\n",
			filepath.Base(src))
		if err := os.WriteFile(out, []byte(header+css), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write:", err)
			os.Exit(1)
		}
		fmt.Println("  ->", out)
	}
}

func compatName(src string) string {
	ext := filepath.Ext(src)
	return strings.TrimSuffix(src, ext) + ".compat" + ext
}

// adaptTextBox handles `text-box: trim-both cap alphabetic` (Chromium 133 /
// Safari 18.2). Old browsers ignore the declaration, so it's harmless to leave
// in place (modern browsers still get the tighter centering) — but without the
// trim the text keeps its full leading and can clip in fixed-height boxes such
// as the LCARS bar heading. There is no CSS equivalent to re-trim, so we append
// targeted compensation inside `@supports not (text-box: …)`, which only
// non-supporting browsers apply. Seeded with the known bar-heading fix; extend
// as on-device testing surfaces more clipped elements.
func adaptTextBox(css string) (string, int) {
	n := strings.Count(css, "text-box:")
	if n == 0 {
		return css, 0
	}
	return css + "\n" + textBoxFallback, n
}

const textBoxFallback = `/* cssgen: compensation for browsers without text-box trimming */
@supports not (text-box: trim-both cap alphabetic) {
  .lcars-text-bar.lcars-text-bar h2,
  .lcars-text-bar.lcars-text-bar h3,
  .lcars-text-bar.lcars-text-bar h4,
  .lcars-text-bar.lcars-text-bar span {
    height: auto;
    align-self: center;
    line-height: 1;
  }
}
`
